### ISSUE TITLE
Possible bug in render_mesh.py

### ISSUE THREAD

**Issue by Twizwei** [MrTornado24/IDE-3D#1]
Hi there, thanks for providing the code! I found some possible bugs when I used `render_mesh.py`. 

- Lack of openGL environment. To solve this, I added `os.environ['PYOPENGL_PLATFORM'] = 'egl'` to the top of the code. 
- Delete the render. I met this error because the render is not deleted at each iteration. To solve this, I added `r.delete()` to the end of each iteration in the for loop. 
- Unsorted image list for video generation. In Line 70, the input image list is not sorted. To fix it, change Line 70 to `img2video(sorted(glob.glob(f"tmp/{id}/*.png")), f"{outdir}/render.mp4")`.

**Comment by MrTornado24** [comment]
Hi, thanks for the correction :)

**Comment by FeiiYin** [comment]
Another note. In my environment, have to set the environment `PYOPENGL_PLATFORM=osmesa` . :-(
