### ISSUE TITLE
Question about dataset.json for inversion

### ISSUE THREAD

**Issue by Twizwei** [MrTornado24/IDE-3D#3]
Hi there, 

In `apps/infer_hybrid_encoder.py`, Line 141: `fname = 'D:/projects/eg3d/data/FFHQ/images512x512/dataset.json' # label list Path. `. Should we prepare `dataset.json` by ourself? Is it possible you could share this file? Thank you so much in advance!

**Comment by MrTornado24** [comment]
Hi, here is the link to [dataset.json](https://drive.google.com/file/d/1fnRy9jSscGUsWMA8H0upy1U5hZ6E0ZbP/view?usp=sharing) for FFHQ. We'll upload the processed FFHQ dataset soon.

**Comment by Twizwei** [comment]
Thank you so much for your help! @MrTornado24
