### ISSUE TITLE
Pose for the real image inversion

### ISSUE THREAD

**Issue by Twizwei** [MrTornado24/IDE-3D#4]
Hi there, sorry for too many questions these days!

It looks like in `apps/infer_hybrid_encoder.py`, it just reads the camera pose from dataset.json. If we want to invert a real image, should we get the pose by using some off-the-shelf pose estimator? Thanks!

**Comment by MrTornado24** [comment]
Please run https://github.com/MrTornado24/IDE-3D/blob/main/dataset_preprocessing/ffhq/preprocess_in_the_wild.py and you'll get a dataset.json with estimated poses.

**Comment by Twizwei** [comment]
Gotcha! Thank you again for your help!
