### ISSUE TITLE
About style transfer

### ISSUE THREAD

**Issue by zhongtao93** [MrTornado24/IDE-3D#5]
Hi, thank you for sharing code.
I have a question about the cartoon demo in [github.io](https://mrtornado24.github.io/IDE-3D/). [cartoon demo](https://mrtornado24.github.io/IDE-3D/videos/3d_transfer.mp4)
![image](https://user-images.githubusercontent.com/15263824/191216530-2cdfd759-7848-4dd1-b01c-026ea6a9d8fc.png)

How to get this style transfer, using a cartoon dataset to transfer learning, then layer blend?
Hoping for your reply!

**Comment by Twizwei** [comment]
It's implemented by a 2D GAN method: [StyleGAN-NADA](https://stylegan-nada.github.io/ )

They actually have included the code here: https://github.com/MrTornado24/ide3d-nada/tree/e8b570aaa51e2b04250908c3a338c3c722511f3f

**Comment by zhongtao93** [comment]
Thanks~
