### ISSUE TITLE
When running painter theres error with dnnlib 

### ISSUE THREAD

**Issue by 1blackbar** [MrTornado24/IDE-3D#6]
import dnnlib
ModuleNotFoundError: No module named 'dnnlib

This is what i get , all dependencies installed fine but on windows some had to be lower versions .

name: ide3d
channels:
  - pytorch
  - nvidia
dependencies:
  - python=3.9
  - pip
  - numpy>=1.20
  - click>=8.0
  - pillow=8.3.1
  - scipy=1.7.1
  - pytorch=1.10.0
  - cudatoolkit=11.3
  - requests=2.27.1
  - tqdm=4.62.3
  - ninja=1.10.2
  - matplotlib=3.5.1
  - imageio=2.9.0
  - pip:
    - imgui==1.4.1
    - glfw==2.5.0
    - pyopengl==3.1.5
    - imageio-ffmpeg==0.4.5
    - pyspng
    - psutil
    - mrcfile
    - tensorboard
    - einops
    - pymcubes
    - pytorch3d

**Comment by MrTornado24** [comment]
Hi, you don't need to install dnnlib. It's a submodule in IDE-3D https://github.com/MrTornado24/IDE-3D/tree/main/dnnlib. Please check the path when you import dnnlib.

**Comment by carlosedubarreto** [comment]
The problem seems to be a hard coded path
![image](https://user-images.githubusercontent.com/4061130/222092698-8f5784ea-1a1c-4a60-8b2b-9e514657667c.png)
