### ISSUE TITLE
Painter/run_UI.py

### ISSUE THREAD

**Issue by nightsky108** [MrTornado24/IDE-3D#7]
D:/projects/IDE-3D/data/ffhq/images512x512/dataset.json
 Can you please share this dataset .json file? When I try to run run_UI.py script, it cause error.

**Comment by MrTornado24** [comment]
Sorry for missing this file. Please download it from https://drive.google.com/file/d/1fnRy9jSscGUsWMA8H0upy1U5hZ6E0ZbP/view?usp=sharing.

**Comment by nightsky108** [comment]
Thank you very much
