### ISSUE TITLE
network_snapshot.pkl was not found

### ISSUE THREAD

**Issue by wanghlsara** [MrTornado24/IDE-3D#8]
Hi, The model file was not found when I ran the following command, Could you please share me the model file(network_snapshot.pkl)? 
>python extract_shapes.py --outdir out --trunc 0.7 --seeds 0-3 \
>   --network **networks/network_snapshot.pkl** --cube_size 1

**Comment by MrTornado24** [comment]
Hi, you should download our pretrained models and change the parameter name to the specific model name in this script.
